# Generated by Django 3.1.3 on 2023-07-19 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('documento', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Documento de indentidad')),
                ('nombres', models.CharField(default=None, max_length=200, verbose_name='Nombre del autor')),
                ('apellidos', models.CharField(default=None, max_length=200, verbose_name='Apellidos')),
                ('image', models.ImageField(default=None, upload_to='images / ')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('correo', models.EmailField(default=None, max_length=254, validators=[django.core.validators.RegexValidator(message='Correo invalido', regex='\\S{1}@\\S{2}\\.\\S{2}')], verbose_name='Correo Electronico')),
                ('telefono', models.CharField(default=None, max_length=20, verbose_name='Telefono')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreu', models.CharField(max_length=200, verbose_name='Nombres')),
                ('correo', models.CharField(default=None, max_length=200, validators=[django.core.validators.RegexValidator(message='Correo invalido', regex='\\S{1}@\\S{2}\\.\\S{2}')], verbose_name='Correo Electronico')),
                ('mensaje', models.TextField(max_length=400, verbose_name='Mensaje')),
                ('fecha_creación', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre del pais')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=20, verbose_name='Descripcion del tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo de Noticias')),
                ('descripcion', models.TextField(max_length=300, verbose_name='Descripcion del tipo de noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo de la notica')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripcion de la noticia')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de creacion')),
                ('autor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='noticias.autor')),
                ('tipo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='noticias.tiponoticia')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='pais',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='noticias.paises'),
        ),
        migrations.AddField(
            model_name='autor',
            name='tipodoc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='noticias.tipodoc'),
        ),
    ]
