# Generated by Django 3.1.3 on 2023-07-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodoc',
            old_name='codigo',
            new_name='descripcion',
        ),
    ]
