# Generated by Django 3.1.3 on 2023-07-21 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20230720_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='correo',
            field=models.EmailField(default=None, max_length=254, validators=[django.core.validators.RegexValidator(message='Correo invalido', regex='\\S{1,}@\\S{2,}\\.\\S{2,}')], verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(default=None, upload_to='images/ '),
        ),
    ]
