# Generated by Django 3.1.3 on 2023-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20230721_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
