# Generated by Django 3.1.3 on 2023-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20230721_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='documento',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Documento de identidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
