# Generated by Django 3.1.3 on 2023-07-23 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20230721_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombres', 'apellidos'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['id'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['descripcion'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'ordering': ['Nombre'], 'verbose_name': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='tipodoc',
            options={'ordering': ['descripcion'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='tiponoticia',
            options={'ordering': ['tipo'], 'verbose_name': 'Tipo de Noticias', 'verbose_name_plural': 'Tipos de Noticias'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='teléfono',
            field=models.CharField(default=None, max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creación',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo de la noticia'),
        ),
    ]
