# Generated by Django 3.1.3 on 2023-08-02 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20230723_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodoc',
            options={'ordering': ['descripcion'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipo de Documentos'},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_creación',
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
        ),
    ]
